### ISSUE TITLE
Exceptions at runtime Demo

### ISSUE THREAD

**Issue by oxaoo** [microth/mateplus#1]
Hello!
I have a problem at runtime the [Demo.java](https://github.com/microth/mateplus/blob/master/src/Demo.java).
I get the following exception:
_java.lang.NullPointerException
    at is2.tag.MFO.getFeatureBits(MFO.java:279)_

That occurs in the following line of code:
        `pipeline = CompletePipeline.getCompletePipeline(options); // initialize pipeline`

I used a combination of different sources and libraries:
- anna-3.3.jar;
- liblinear-1.94.jar;
- standford-corenlp-3.4.jar
- mateplus.jar
- CoNLL2009-ST-English-ALL.anna-3.3.lemmatizer.model
- CoNLL2009-ST-English-ALL.anna-3.3.parser.model
- CoNLL2009-ST-English-ALL.anna-3.3.postagger.model
- CoNLL2009-ST-English-ALL.anna-3.3.srl-4.1.srl.model

and so:
- anna-3.3.jar;
- liblinear-1.94.jar;
- standford-corenlp-3.4.jar
- mateplus.jar
- CoNLL2009-ST-English-ALL.anna-3.3.lemmatizer.model
- CoNLL2009-ST-English-ALL.anna-3.3.parser.model
- CoNLL2009-ST-English-ALL.anna-3.3.postagger.model
- srl-EMNLP14+fs-eng.model

and so:
- anna-3.6.jar
- liblinear-java-1.95.jar
- stanford-corenlp-3.6.0.jar
- mateplus.jar
- tagger-eng-4M-v36.mdl
- parser-eng-12M-v36.mdl
- lemmatizer-eng-4M-v36.mdl
- srl-EMNLP14+fs-eng.model

But it was not able to solve this problem.
I am hope for your help!

Full stack exceptions:
_38.18.542  is2.data.ParametersFloat 121:read ->        read parameters 4000001 not zero 275524
38.18.549  is2.data.Cluster 113:<init> ->              Read cluster with 0 words 
38.18.550  is2.lemmatizer.Lemmatizer 192:readModel ->  Loading data finished. 
38.18.550  is2.lemmatizer.Lemmatizer 194:readModel ->  number of params  4000001
38.18.550  is2.lemmatizer.Lemmatizer 195:readModel ->  number of classes 89
**java.lang.NullPointerException
    at is2.tag.MFO.getFeatureBits(MFO.java:279)**
    at is2.tag.ExtractorT2.initValues(ExtractorT2.java:198)
    at is2.tag.Tagger.readModel(Tagger.java:124)
    at is2.tag.Tagger.<init>(Tagger.java:55)
    at is2.tag.Tagger.<init>(Tagger.java:66)
    at se.lth.cs.srl.util.BohnetHelper.getTagger(BohnetHelper.java:26)
    at se.lth.cs.srl.languages.Language.getPreprocessor(Language.java:114)
    at se.lth.cs.srl.CompletePipeline.getCompletePipeline(CompletePipeline.java:68)
    at com.github.oxaoo.srl.Demo.<init>(Demo.java:63)
    at com.github.oxaoo.srl.Demo.main(Demo.java:53)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
38.18.624  is2.parser.Parser 188:readModel ->          Reading data started
38.19.451  is2.data.Cluster 113:<init> ->              Read cluster with 4000001 words 
38.19.451  is2.parser.ParametersFloat 101:read ->      read parameters 0 not zero 0
38.19.451  is2.parser.Parser 201:readModel ->          parsing -- li size 0
38.19.455  is2.parser.Parser 211:readModel ->          Stacking false
38.19.456  is2.parser.Extractor 85:initStat ->         shift init (d5) 
java.lang.NegativeArraySizeException
    at is2.parser.Edges.read(Edges.java:153)
    at is2.parser.Parser.readModel(Parser.java:219)
    at is2.parser.Parser.<init>(Parser.java:71)
    at is2.parser.Parser.<init>(Parser.java:83)
    at se.lth.cs.srl.util.BohnetHelper.getParser(BohnetHelper.java:43)
    at se.lth.cs.srl.languages.Language.getPreprocessor(Language.java:118)
    at se.lth.cs.srl.CompletePipeline.getCompletePipeline(CompletePipeline.java:68)
    **at com.github.oxaoo.srl.Demo.<init>(Demo.java:63)
    at com.github.oxaoo.srl.Demo.main(Demo.java:53)**
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Loading pipeline from src\main\resources\external\CoNLL2009-ST-English-ALL.anna-3.3.srl-4.1.srl.model
Exception in thread "main" java.lang.NoClassDefFoundError: liblinear/InvalidInputDataException
    at java.lang.Class.getDeclaredFields0(Native Method)
    at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
    at java.lang.Class.getDeclaredField(Class.java:2068)
    at java.io.ObjectStreamClass.getDeclaredSUID(ObjectStreamClass.java:1703)
    at java.io.ObjectStreamClass.access$700(ObjectStreamClass.java:72)
    at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:484)
    at java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:472)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.io.ObjectStreamClass.<init>(ObjectStreamClass.java:472)
    at java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:369)
    at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:598)
    at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1623)
    at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
    at se.lth.cs.srl.pipeline.AbstractStep.readModels(AbstractStep.java:83)
    at se.lth.cs.srl.pipeline.AbstractStep.readModels(AbstractStep.java:68)
    at se.lth.cs.srl.pipeline.Pipeline.fromZipFile(Pipeline.java:276)
    at se.lth.cs.srl.pipeline.Pipeline.fromZipFile(Pipeline.java:283)
    at se.lth.cs.srl.pipeline.Reranker.<init>(Reranker.java:84)
    at se.lth.cs.srl.CompletePipeline.getCompletePipeline(CompletePipeline.java:76)
    at com.github.oxaoo.srl.Demo.<init>(Demo.java:63)
    at com.github.oxaoo.srl.Demo.main(Demo.java:53)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.ClassNotFoundException: liblinear.InvalidInputDataException
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 29 more_

**Comment by microth** [comment]
Hi Alexander,

Thank you for your interest in mateplus!

The error message is thrown by one of the preprocessing components from the original matetools project (the is2.\* package is part of the library anna-x.x.jar). The cause for this is most likely that the model files you are using are incompatible with your version of the downloaded library (3.3 vs. 3.6). To resolve this issue, please remove anna-3.6.jar and make sure that only anna-3.3.jar is part of your classpath. If this does not help, you might also want to check whether your model files (lemmatizer, parser, tagger) are complete and re-download them otherwise. A simple way to ensure that they are not corrupt is to unzip them (each model file is actually a zip archive).

If none of the above steps helped, you could also try and consult the authors of the matetools preprocessing components directly. They probably know their code better than I do. :)

Cheers,
Michael
