### ISSUE TITLE
.vectors file not found

### ISSUE THREAD

**Issue by ebronstein** [microth/mateplus#5]
I am running mateplus with the FrameNet extensions using scripts/parse-framenet.sh and I am getting the following error:

`
Reading initial word vectors ...
java.io.FileNotFoundException: /var/folders/gs/_kdj8q4s2536xk3y6kngfrp00000gn/T/glv4299719639507468829.txt.vectors (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at java.io.FileReader.<init>(FileReader.java:58)
	at se.lth.cs.srl.util.ExternalProcesses.createvecs(ExternalProcesses.java:192)
	at se.lth.cs.srl.CompletePipeline.parseFullDocument(CompletePipeline.java:214)
	at se.lth.cs.srl.CompletePipeline.main(CompletePipeline.java:162)
`

It seems that it's not finding the .vectors temporary file. I looked in the `/var/folders/gs/_kdj8q4s2536xk3y6kngfrp00000gn/T/` directory, and these are the files that are there:

`glv4299719639507468829.txt`
`glv4299719639507468829.txt.coocs`
`glv4299719639507468829.txt.grad`
`glv4299719639507468829.txt.init`
`glv4299719639507468829.txt.vocab`

As you can see, the `.vectors` file isn't there. It seems that the `processtmp.sh` script in the `models/glove10a` directory should be writing to the `.vectors` file in the following line:

`perl $GLOVEDIR/removeBiasCenterAndScale.pl $SAVE_FILE.txt $SCALE_FILE $1.vocab > $1.vectors`

Apparently, this isn't happening. Do you have any suggestions on what I should try? I think I have set all of the script variables correctly because I ran the non-FrameNet-extended version using `scripts.parse.sh` and that worked fine.

Thank you in advance!

**Comment by microth** [comment]
Based on your description, it sounds like removeBiasCenterAndScale.pl throws an error and never gets to the mentioned line. Please try to run it manually to see what the error is.
