### ISSUE TITLE
Error running parse.sh

### ISSUE THREAD

**Issue by mosynaq** [microth/mateplus#6]
I downloaded all dependencies and placed them where they should be. But after issuing `./scripts/parse.sh i can see you.` I get the following:

```
MYNAME@mint /media/MYNAME/windowsmountedpartition/Libraries/mateplus $ ./scripts/parse.sh I can see you.
54.4.489   is2.data.ParametersFloat 121:read ->        read parameters 134217727 not zero 296071
54.4.494   is2.data.Cluster 113:<init> ->              Read cluster with 0 words 
54.4.495   is2.lemmatizer.Lemmatizer 192:readModel ->  Loading data finished. 
54.4.495   is2.lemmatizer.Lemmatizer 194:readModel ->  number of params  134217727
54.4.495   is2.lemmatizer.Lemmatizer 195:readModel ->  number of classes 92
54.9.174   is2.data.ParametersFloat 121:read ->        read parameters 134217727 not zero 1613201
54.9.174   is2.data.Cluster 113:<init> ->              Read cluster with 0 words 
54.9.175   is2.tag.Lexicon 103:<init> ->               Read lexicon with 0 words 
54.9.176   is2.tag.Tagger 141:readModel ->             Loading data finished. 
54.9.183   is2.parser.Parser 188:readModel ->          Reading data started
54.9.217   is2.data.Cluster 113:<init> ->              Read cluster with 0 words 
54.15.32   is2.parser.ParametersFloat 101:read ->      read parameters 134217727 not zero 19957525
54.15.32   is2.parser.Parser 201:readModel ->          parsing -- li size 134217727
54.15.37   is2.parser.Parser 211:readModel ->          Stacking false
54.15.37   is2.parser.Extractor 56:initStat ->         mult  (d4) 
Used parser   class is2.parser.Parser
Creation date 2012.11.02 14:33:53
Training data CoNLL2009-ST-English-ALL.txt.crossannotated
Iterations    10 Used sentences 10000000
Cluster       null
54.15.39   is2.parser.Parser 240:readModel ->          Reading data finnished
54.15.40   is2.parser.Extractor 56:initStat ->         mult  (d4) 
Loading pipeline from models/srl-EMNLP14+fs-eng.model
Exception in thread "main" java.io.InvalidObjectException: enum constant WordEmbeddingArg045 does not exist in class se.lth.cs.srl.features.FeatureName
	at java.io.ObjectInputStream.readEnum(ObjectInputStream.java:1958)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1532)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at java.util.HashMap.readObject(HashMap.java:1402)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2122)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2013)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2231)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2155)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2013)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at se.lth.cs.srl.pipeline.Pipeline.fromZipFile(Pipeline.java:190)
	at se.lth.cs.srl.pipeline.Pipeline.fromZipFile(Pipeline.java:219)
	at se.lth.cs.srl.pipeline.Reranker.<init>(Reranker.java:74)
	at se.lth.cs.srl.CompletePipeline.getCompletePipeline(CompletePipeline.java:41)
	at se.lth.cs.srl.CompletePipeline.main(CompletePipeline.java:93)
Caused by: java.lang.IllegalArgumentException: No enum constant se.lth.cs.srl.features.FeatureName.WordEmbeddingArg045
	at java.lang.Enum.valueOf(Enum.java:238)
	at java.io.ObjectInputStream.readEnum(ObjectInputStream.java:1955)
	... 21 more
``` 
My `models` directory includes:
```
argmodel.dat
CoNLL2009-ST-English-ALL.anna-3.3.lemmatizer.model
CoNLL2009-ST-English-ALL.anna-3.3.parser.model
CoNLL2009-ST-English-ALL.anna-3.3.postagger.model
CoNLL2009-ST-English-ALL.anna-3.3.srl-4.1.srl.model
engmalt.linear-1.7.mco
excludes.map
framenet.frame.element.map
gradsq.txt
graph
graph.gz
idmodel.dat
parser.conf
parser.conf.bak
reqData.jobj
requires.map
scaleparams.txt
sparsegraph
sparsegraph.gz
srl-EMNLP14+fs-eng.model
srl-TACL15-eng.model
vectors.txt
vocab.txt
```
and my `lib` directory has:
```
anna-3.3.jar
cooccur
cooccur++
demo.sh
glove
liblinear-1.51-with-deps.jar
liblinear-java-1.95.jar
opennlp-maxent-3.0.2-incubating.jar
opennlp-tools-1.5.2-incubating.jar
processtmp.sh
removeBiasCenterAndScale.pl
seg.jar
shuffle
srl.jar
srl-src.jar
stanford-corenlp-3.7.0.jar
stanford-parser.jar
vocab_count
whatswrong-0.2.3.jar
```
I use mint 18.1.
What is the problem?

**Comment by microth** [comment]
What does the classpath in your parse.sh look like? If the srl.jar library from mate-tools is in your classpath, classes from mateplus with the same name will not be loaded (WordEmbeddingArg045 is a new constant in FeatureName, defined in mate-tools but not in mateplus).

**Comment by mosynaq** [comment]
On the last line I have this:
`$JAVA -cp "lib/*:mateplus.jar" -Xmx6g se.lth.cs.srl.CompletePipeline eng -lemma $LEMMA_MODEL -parser $PARSER_MODEL -tagger $POS_MODEL -srl models/srl-EMNLP14+fs-eng.model $RERANKER $TOKENIZE -test $1`

**Comment by mosynaq** [comment]
Simply removing `srl.jar` from classpath worked! It should NOT be in `./libs`!
